# Generated by Django 4.1.6 on 2023-02-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='good product'),
            preserve_default=False,
        ),
    ]
